config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save

    redirect_to flats_path
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy

    redirect_to flats_path
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)

    redirect_to flat_path(@flat)
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :number_of_guests, :price_per_night)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 m-auto">
      <h2>Edit an existing flat</h2>
      <%= simple_form_for(@flat) do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :description %>
        <%= f.input :price_per_night %>
        <%= f.input :number_of_guests %>
        <%= f.submit "Save changes", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container">
  <h1>All available flats (<%= @flats.count%>)</h1>
  <div class="cards d-flex">
  <% @flats.each do |flat| %>
    <div class="card">
      <div class="card-info">
        <%= flat.name%>
        <br>
        <%= flat.address %>
        <div class="card-number-info d-flex">
          <div class="guests fas fa-user-friends">
            <%= flat.number_of_guests %>
          </div>
          <div class="price fas fa-tag">
            <%= flat.price_per_night %>
          </div>
        </div>
      </div>
      <div class="buttons d-flex">
        <%= link_to "More Info", flat_path(flat), class: "more-info"  %>
        <%= link_to "Edit", edit_flat_path(flat), class: "edit"  %>
        <%= link_to "Remove", flat_path(flat), method: :delete  %>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 m-auto">
      <h2>Add a new flat</h2>
      <%= simple_form_for(@flat) do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :description %>
        <%= f.input :price_per_night %>
        <%= f.input :number_of_guests %>
        <%= f.submit "Add flat", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="map" style="background-image: url('https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200')"></div>

<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="flat-show-card">
        <h1><%= @flat.name %></h1>
        <p><%= @flat.address %></p>
      </div>
      <div class="flat-show-card">
        <h3>A bit more about this flat...</h3>
        <p><%= @flat.description %></p>
        <div class="map" style="background-image: url('https://maps.googleapis.com/maps/api/staticmap?center=5 Queensmill Road London SW6 6JP&zoom=13&scale=2&size=1000x1000&maptype=roadmap&markers=color:red%7C5 Queensmill Road London SW6 6JP&key=AIzaSyBtaHK-BLhBg7TruJu8iKk_wETqZMJM-GY')"></div>
      </div>
    </div>
    <div class="col-4">
      <div class="flat-show-card">
        <h5>Book this place!</h5>
      </div>
      <div class="flat-show-card">
        <h3>Details</h3>
        <div class="flex">
          <p class="fas fa-user-friends">    <%= @flat.number_of_guests%></p>
          <p class="fas fa-tag">    <%= @flat.price_per_night %></p>
        </div>
      </div>
      <div class="flat-show-card"></div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar">
      <h2 class="navbar-brand"><%= link_to "FlatChad", flats_path %></h2>
      <%= link_to "Add Flat", new_flat_path, class: "btn btn-outline-primary" %>
    </div>
    <%= yield %>
  </body>
</html>